[versions]
# Build & Toolchain
agp = "8.13.2"
converter-gson = "3.0.0"
kotlin = "2.3.0"
ksp = "2.2.20-2.0.3"

# Database
logging-interceptor = "5.3.2"
room = "2.8.4"

# Data-Model
kotlinx-serialization = "1.9.0"

# AndroidX Core
core-ktx = "1.17.0"

# Navigation
navigation-compose = "2.8.4"

# DataStore
datastore = "1.1.1"

# Coroutines
coroutines = "1.9.0"

# DocumentFile
documentfile = "1.0.1"

# LLM Inference
llama = "3.4.1"

# Compose
compose-bom = "2025.12.01"
compose-material3 = "1.5.0-alpha11"
material = "1.13.0"
activity-compose = "1.12.2"
material-icons-extended = "1.7.8"

# Lifecycle (for ViewModel)
lifecycle = "2.10.0"
junit = "4.13.2"
junit-version = "1.3.0"
espresso-core = "3.7.0"
appcompat = "1.7.1"
ui-text = "1.10.0"

[libraries]
# Database
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

#Data-Model
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converter-gson" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# AndroidX Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }

# Navigation
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }

# DataStore
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# Coroutines
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# DocumentFile
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }

# LLM Inference
llama-java = { module = "de.kherud:llama", version.ref = "llama" }

# Lifecycle (ViewModel)
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

# Compose & UI
androidx-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

# Debug tools
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-compose-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "ui-text" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converter-gson" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }